"use client";

import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Bell, Clock, AlertTriangle, Mail, MessageSquare, Smartphone, MessageCircle } from "lucide-react";
import { api } from "@/lib/api-client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { PushToggle } from "@/components/push-toggle";

type Prefs = {
  receiveExpirationAlerts: boolean | null;
  receiveLowStockAlerts: boolean | null;
  receiveAlertsByEmail: boolean | null;
  receiveAlertsByTeams: boolean | null;
  receiveAlertsByPush: boolean | null;
  receiveAlertsBySms: boolean | null;
  phone: string | null;
};

type IntegrationsStatus = {
  emailConfigured: boolean;
  teamsConfigured: boolean;
  pushConfigured: boolean;
  smsConfigured: boolean;
};

export default function AlertSettingsPage() {
  const qc = useQueryClient();
  const { data } = useQuery({
    queryKey: ["me-alerts"],
    queryFn: () => api.get<Prefs>("/api/me/alerts"),
  });
  const integrations = useQuery({
    queryKey: ["integrations-status"],
    queryFn: () => api.get<IntegrationsStatus>("/api/integrations/status"),
  });

  const [expirations, setExpirations] = useState(true);
  const [lowStock, setLowStock] = useState(true);
  const [byEmail, setByEmail] = useState(false);
  const [byTeams, setByTeams] = useState(false);
  const [byPush, setByPush] = useState(false);
  const [bySms, setBySms] = useState(false);
  const [phone, setPhone] = useState("");

  useEffect(() => {
    if (data) {
      setExpirations(data.receiveExpirationAlerts !== false);
      setLowStock(data.receiveLowStockAlerts !== false);
      setByEmail(data.receiveAlertsByEmail === true);
      setByTeams(data.receiveAlertsByTeams === true);
      setByPush(data.receiveAlertsByPush === true);
      setBySms(data.receiveAlertsBySms === true);
      setPhone(data.phone ?? "");
    }
  }, [data]);

  const save = useMutation({
    mutationFn: () =>
      api.patch("/api/me/alerts", {
        receiveExpirationAlerts: expirations,
        receiveLowStockAlerts: lowStock,
        receiveAlertsByEmail: byEmail,
        receiveAlertsByTeams: byTeams,
        receiveAlertsByPush: byPush,
        receiveAlertsBySms: bySms,
        phone: phone.trim() ? phone.trim() : null,
      }),
    onSuccess: () => {
      toast.success("Saved.");
      qc.invalidateQueries({ queryKey: ["me-alerts"] });
    },
    onError: (e) => toast.error(String(e)),
  });

  return (
    <div className="max-w-xl space-y-4">
      <header>
        <h1 className="text-2xl font-bold flex items-center gap-2">
          <Bell className="h-6 w-6" /> Alert settings
        </h1>
        <p className="text-sm text-muted-foreground">
          Choose which notifications you receive and where they're sent.
        </p>
      </header>

      <Card>
        <CardHeader>
          <CardTitle>What I want to be alerted about</CardTitle>
          <CardDescription>
            Generated by the system check (manual now; daily cron once deployed).
            Medics never receive these by default; only admins and managers.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <Toggle
            label="Expiration alerts"
            description="Items expiring within 30 days, plus anything already expired."
            icon={Clock}
            checked={expirations}
            onChange={setExpirations}
          />
          <Toggle
            label="Low-stock alerts"
            description="Items at or below their low-stock threshold."
            icon={AlertTriangle}
            checked={lowStock}
            onChange={setLowStock}
          />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Where to send them</CardTitle>
          <CardDescription>
            In-app notifications are always on. Email, Teams, and Push are off by default.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <Toggle
            label="Email"
            description={
              integrations.data?.emailConfigured
                ? "Alerts sent to your account email address."
                : "⚠ SMTP isn't configured yet — see Admin → Integrations."
            }
            icon={Mail}
            checked={byEmail}
            onChange={setByEmail}
            disabled={integrations.data && !integrations.data.emailConfigured}
          />
          <Toggle
            label="Microsoft Teams"
            description={
              integrations.data?.teamsConfigured
                ? "Alerts posted to the configured Teams channel webhook."
                : "⚠ Teams webhook isn't configured yet — see Admin → Integrations."
            }
            icon={MessageSquare}
            checked={byTeams}
            onChange={setByTeams}
            disabled={integrations.data && !integrations.data.teamsConfigured}
          />
          <Toggle
            label="Push notifications (this browser / device)"
            description={
              integrations.data?.pushConfigured
                ? "Pop-up notifications on whichever browsers and devices you enable. Works on PC + Android. iOS PWA push is unreliable — use SMS instead."
                : "⚠ VAPID keys not configured yet — see Admin → Integrations."
            }
            icon={Smartphone}
            checked={byPush}
            onChange={setByPush}
            disabled={integrations.data && !integrations.data.pushConfigured}
          />
          <Toggle
            label="SMS text message"
            description={
              integrations.data?.smsConfigured
                ? "Alerts texted to your phone. Best for iOS users — push is unreliable on iOS PWAs."
                : "⚠ Twilio not configured yet — see Admin → Integrations."
            }
            icon={MessageCircle}
            checked={bySms}
            onChange={setBySms}
            disabled={integrations.data && !integrations.data.smsConfigured}
          />
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Phone number</CardTitle>
          <CardDescription>
            Required for SMS alerts. Use E.164 format (e.g. <code>+14145551234</code>) — country code + number, no spaces or dashes.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-2">
          <Label htmlFor="phone">Mobile number</Label>
          <Input
            id="phone"
            type="tel"
            value={phone}
            onChange={(e) => setPhone(e.target.value)}
            placeholder="+14145551234"
          />
          <p className="text-xs text-muted-foreground">
            Standard text message rates apply. Reply STOP to opt out at any time.
          </p>
        </CardContent>
      </Card>

      {byPush && integrations.data?.pushConfigured && (
        <Card>
          <CardHeader>
            <CardTitle>Push devices</CardTitle>
            <CardDescription>
              Push has to be enabled on each browser / device individually (you'll see one entry per browser you sign in from).
            </CardDescription>
          </CardHeader>
          <CardContent>
            <PushToggle pushConfigured={integrations.data.pushConfigured} />
          </CardContent>
        </Card>
      )}

      <div className="flex justify-end">
        <Button onClick={() => save.mutate()} disabled={save.isPending}>Save preferences</Button>
      </div>
    </div>
  );
}

function Toggle({
  label,
  description,
  icon: Icon,
  checked,
  onChange,
  disabled,
}: {
  label: string;
  description: string;
  icon: typeof Bell;
  checked: boolean;
  onChange: (v: boolean) => void;
  disabled?: boolean;
}) {
  return (
    <label className={`flex items-start gap-3 ${disabled ? "opacity-60 cursor-not-allowed" : "cursor-pointer"}`}>
      <input
        type="checkbox"
        className="mt-1 h-5 w-5"
        checked={checked && !disabled}
        disabled={disabled}
        onChange={(e) => onChange(e.target.checked)}
      />
      <div>
        <div className="font-medium flex items-center gap-2">
          <Icon className="h-4 w-4" /> {label}
        </div>
        <p className="text-xs text-muted-foreground">{description}</p>
      </div>
    </label>
  );
}
